--- a/Makefile	1970-01-01 00:00:00.000000000 +0000
+++ b/Makefile	2015-09-01 00:00:00.000000000 +0000
@@ -21,8 +21,8 @@
 DISPLAY = SDL
 #DISPLAY = X11
 
-#KEYBOARD = OLD
-KEYBOARD = NEW
+KEYBOARD = OLD
+#KEYBOARD = NEW
 
 #----------- code ------------
